version = 1

[merge]
automerge_label = "ðŸš€ merge it!"
blocking_labels = ["Status: WIP", "Status: Do Not Merge"]
method = ["squash", "merge"]

[merge.automerge_dependencies]
# only auto merge "minor" and "patch" version upgrades.
# do not automerge "major" version upgrades.
versions = ["minor", "patch"]
usernames = ["renovate"]

