[dev]
  command = "yarn start"
  targetPort = 8000
  framework = "#custom"

[build]
  publish = "packages/paste-website/public/"
  command = "yarn build:js && yarn build:tokens && yarn build:website"

[build.environment]
  YARN_VERSION = "3.0.2"
  YARN_ENABLE_GLOBAL_CACHE = "true"
  YARN_GLOBAL_FOLDER = "/opt/buildhome/.yarn_cache"

[context.deploy-preview]
  # only do a preview deply when there is a website change
  ignore = "git diff --quiet HEAD^ main -- packages/paste-website packages/paste-theme-designer"

[context.deploy-preview.environment]
  GATSBY_ENVIRONMENT_CONTEXT = "deploy-preview"

[context.branch-deploy.environment]
  GATSBY_ENVIRONMENT_CONTEXT = "branch-deploy"

[context.production.environment]
  GATSBY_ENVIRONMENT_CONTEXT = "production"

[functions]
  directory = "functions"
  external_node_modules = ["chrome-aws-lambda", "puppeteer-core"]

[[redirects]]
  from = "/tokens/how-to-compose-custom-ui-with-tokens"
  to = "/customization/composing-custom-components-with-design-tokens"

[[headers]]
  for = "/*"
  [headers.values]
    X-Shenanigans = "none"

