[build]
  command = "yarn build && yarn build:theme-designer"

[build.environment]
  YARN_ENABLE_GLOBAL_CACHE = "true"
  YARN_GLOBAL_FOLDER = "/opt/buildhome/.yarn_cache"

[context.deploy-preview.environment]
  ENVIRONMENT_CONTEXT = "deploy-preview"

[context.branch-deploy.environment]
  ENVIRONMENT_CONTEXT = "branch-deploy"

[context.production.environment]
  ENVIRONMENT_CONTEXT = "production"

[[headers]]
  for = "/*"
  [headers.values]
    X-Shenanigans = "none"
