# name: Pull Request Categorizer

# on: pull_request

# jobs:
#   pr-categorizer:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/labeler@v3
#         with:
#           repo-token: "${{ secrets.GITHUB_TOKEN }}"
#           sync-labels: true
