name: Remove VRT Label

on:
  pull_request:
    types: [synchronize]

jobs:
  remove-test-label:
    if: ${{ github.event.label.name == 'ğŸ•µğŸ»â€â™€ï¸ Run website visual regression' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-ecosystem/action-remove-labels@v1
        with:
          labels: "ğŸ•µğŸ»â€â™€ï¸ Run website visual regression"
